### PR TITLE
Feature/olejsc/gui prefabs

### PR DESCRIPTION
**Pull request by olejsc**
- Added GUI prefab for events (single and multiple choice), aswell as GUI for the main Phone screen. - Removed old obsolete tests

- Created some folder structure for Prefabs
- Icons for apps added w/ own folder
- Folder for Materials added.

### CODE REVIEW

**Comment by MathiasFl** [comment]
Helst unngå å legge med meta filer.

**Comment by olejsc** [comment]
> Helst unngå å legge med meta filer.

Har forstått d sånn at meta-filer e anbefalt å ha me selv i VCS: https://docs.unity3d.com/Manual/ExternalVersionControlSystemSupport.html

Men hvis dem ikke e nødvendig, så burde dem naturlivis legges i gitignore.

**Comment by MathiasFl** [comment]
Sett, my bad leste feil :(
All is good then :+1:

**Comment by aslakkh** [comment]
Mangler app-ikoner?

**Pull request merged**
